spring:
  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist
  # Database
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/network?autoReconnect=true
    username: root
    password: 1234
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    open-in-view: false
    generate-ddl: true
# algorithm : HmacSHA256 / key : hmacTest / text: networkjwt
jwt:
  secretKey: ikqAkw/p1sOjWVwwIOqw+rURBaq3inS1yfNmppYsRAE=
  token:
    access-expiration-time: 1800000 # 30분
    refresh-expiration-time: 86400000 # 1일
